import { test } from '@playwright/test';
import { faker } from '@faker-js/faker';
import {AddCustomerPage} from '../../../src/pages/manager/AddCustomerPage';
import { CustomersListPage } from '../../../src/pages/manager/CustomersListPage';
test('Assert manager can add new customer', async ({ page }) => {
  const addCustomer = new AddCustomerPage(page);
  const customersListPage = new CustomersListPage(page);
  const firstName = faker.person.firstName();
  const lastName = faker.person.lastName();
  const postCode = faker.location.zipCode();  
  await addCustomer.open();
  await addCustomer.fillFirstNameInputField(firstName);
  await addCustomer.fillLastNameInputField(lastName);
  await addCustomer.fillPostCodeInputField(postCode);
  await addCustomer.setupAlertHandler();
  await addCustomer.clickAddCustomerFormButton();
  await page.reload();
 await customersListPage.open();
  await customersListPage.assertLastRowFirstNameEquals(firstName);
  await customersListPage.assertLastRowLastNameEquals(lastName);
  await customersListPage.assertLastRowPostalCodeEquals(postCode);
  await customersListPage.assertLastRowAccountNumberIsEmpty();
});
